# Generated by Django 3.2.1 on 2021-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='pizza.Topping'),
        ),
    ]
